site_name: Miyu Docs
site_url: https://miyu-docs.qwewqa.xyz/
repo_url: https://github.com/qwewqa/miyu-bot
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
plugins:
  - i18n:
      default_language: en
      languages:
        en: English
        zh_TW: 繁體中文
        ja: 日本語
  - awesome-pages
markdown_extensions:
  - admonition
  - pymdownx.details
  - toc:
      permalink: true