-- upgrade --
ALTER TABLE "channel" ALTER COLUMN "timezone" DROP DEFAULT;
ALTER TABLE "channel" ALTER COLUMN "timezone" DROP NOT NULL;
ALTER TABLE "channel" ALTER COLUMN "timezone" TYPE VARCHAR(31) USING "timezone"::VARCHAR(31);
ALTER TABLE "channel" ALTER COLUMN "language" DROP DEFAULT;
ALTER TABLE "channel" ALTER COLUMN "language" DROP NOT NULL;
ALTER TABLE "channel" ALTER COLUMN "language" TYPE VARCHAR(15) USING "language"::VARCHAR(15);
ALTER TABLE "guild" ALTER COLUMN "timezone" DROP DEFAULT;
ALTER TABLE "guild" ALTER COLUMN "timezone" DROP NOT NULL;
ALTER TABLE "guild" ALTER COLUMN "timezone" TYPE VARCHAR(31) USING "timezone"::VARCHAR(31);
ALTER TABLE "guild" ALTER COLUMN "prefix" DROP DEFAULT;
ALTER TABLE "guild" ALTER COLUMN "prefix" DROP NOT NULL;
ALTER TABLE "guild" ALTER COLUMN "prefix" TYPE VARCHAR(63) USING "prefix"::VARCHAR(63);
ALTER TABLE "guild" ALTER COLUMN "language" DROP DEFAULT;
ALTER TABLE "guild" ALTER COLUMN "language" DROP NOT NULL;
ALTER TABLE "guild" ALTER COLUMN "language" TYPE VARCHAR(15) USING "language"::VARCHAR(15);
ALTER TABLE "user" ALTER COLUMN "timezone" DROP DEFAULT;
ALTER TABLE "user" ALTER COLUMN "timezone" DROP NOT NULL;
ALTER TABLE "user" ALTER COLUMN "timezone" TYPE VARCHAR(31) USING "timezone"::VARCHAR(31);
ALTER TABLE "user" ALTER COLUMN "prefix" DROP DEFAULT;
ALTER TABLE "user" ALTER COLUMN "prefix" DROP NOT NULL;
ALTER TABLE "user" ALTER COLUMN "prefix" TYPE VARCHAR(63) USING "prefix"::VARCHAR(63);
ALTER TABLE "user" ALTER COLUMN "language" DROP DEFAULT;
ALTER TABLE "user" ALTER COLUMN "language" DROP NOT NULL;
ALTER TABLE "user" ALTER COLUMN "language" TYPE VARCHAR(15) USING "language"::VARCHAR(15);

UPDATE channel SET timezone=NULL where timezone='';
UPDATE channel SET language=NULL where language='';
UPDATE guild SET timezone=NULL where timezone='';
UPDATE guild SET language=NULL where language='';
UPDATE guild SET prefix=NULL where prefix='';
UPDATE "user" SET timezone=NULL where timezone='';
UPDATE "user" SET language=NULL where language='';
UPDATE "user" SET prefix=NULL where prefix='';
-- downgrade --
ALTER TABLE "user" ALTER COLUMN "timezone" TYPE VARCHAR(31) USING "timezone"::VARCHAR(31);
ALTER TABLE "user" ALTER COLUMN "timezone" SET DEFAULT '';
ALTER TABLE "user" ALTER COLUMN "prefix" TYPE VARCHAR(63) USING "prefix"::VARCHAR(63);
ALTER TABLE "user" ALTER COLUMN "prefix" SET DEFAULT '';
ALTER TABLE "user" ALTER COLUMN "language" TYPE VARCHAR(15) USING "language"::VARCHAR(15);
ALTER TABLE "user" ALTER COLUMN "language" SET DEFAULT '';
ALTER TABLE "guild" ALTER COLUMN "timezone" TYPE VARCHAR(31) USING "timezone"::VARCHAR(31);
ALTER TABLE "guild" ALTER COLUMN "timezone" SET DEFAULT '';
ALTER TABLE "guild" ALTER COLUMN "prefix" TYPE VARCHAR(63) USING "prefix"::VARCHAR(63);
ALTER TABLE "guild" ALTER COLUMN "prefix" SET DEFAULT '';
ALTER TABLE "guild" ALTER COLUMN "language" TYPE VARCHAR(15) USING "language"::VARCHAR(15);
ALTER TABLE "guild" ALTER COLUMN "language" SET DEFAULT '';
ALTER TABLE "channel" ALTER COLUMN "timezone" TYPE VARCHAR(31) USING "timezone"::VARCHAR(31);
ALTER TABLE "channel" ALTER COLUMN "timezone" SET DEFAULT '';
ALTER TABLE "channel" ALTER COLUMN "language" TYPE VARCHAR(15) USING "language"::VARCHAR(15);
ALTER TABLE "channel" ALTER COLUMN "language" SET DEFAULT '';
